//:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
//::                                                                         ::
//::     Antonio Manuel Rodrigues Manso                                      ::
//::                                                                         ::
//::     I N S T I T U T O    P O L I T E C N I C O   D E   T O M A R        ::
//::     Escola Superior de Tecnologia de Tomar                              ::
//::     e-mail: manso@ipt.pt                                                ::
//::     url   : http://orion.ipt.pt/~manso                                  ::
//::                                                                         ::
//::     This software was build with the purpose of investigate and         ::
//::     learning.                                                           ::
//::                                                                         ::
//::                                                               (c)2020   ::
//:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
//////////////////////////////////////////////////////////////////////////////
package templarCoin.gui;

import java.awt.GridLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import templarCoin.core.Candidato;
import templarCoin.core.Eleitor;
import templarCoin.core.TemplarCoin;
import templarCoin.core.Transaction;
import templarCoin.core.ListCandidates;
import templarCoin.utils.ElectionUtils;

/**
 *
 * @author manso
 */
public class TemplarCoinGUI extends javax.swing.JFrame {

    public static String fileTemplarCpoin = "templarCoin.obj";
    TemplarCoin coin;
    protected ListCandidates lista;
    JList candidatesList;
    
    
    
    public void populateCand(){
	//lstCandidates.setModel(ListCandidates.getListData());
	lstCandidates.setModel(ElectionUtils.getListModel(this.lista.getLista()));
    }
    
    
    /**
     * Creates new form TemplarCoinGUI
     */
    public TemplarCoinGUI() {
        initComponents();
        coin = new TemplarCoin();
        try {
            coin = TemplarCoin.load(fileTemplarCpoin);
        } catch (Exception e) {
        }
        txtLeger.setText(coin.toString());
        txtBlochains.setText(coin.getSecureLedger().toString());
        setSize(800, 600);
        setLocationRelativeTo(null);
	
	candidatesList = new JList();
	
	//populateCand();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLeger = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtBlochains = new javax.swing.JTextArea();
        tpTransaction = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        pnTransaction = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        txtValue = new javax.swing.JTextField();
        btRegister = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pnEleitores = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstUsers = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        pnCandidatos = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstCandidates = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Templar coin Demo");

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(234, 0));

        txtLeger.setColumns(20);
        txtLeger.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txtLeger.setRows(5);
        jScrollPane1.setViewportView(txtLeger);

        jTabbedPane1.addTab("Ledger", new javax.swing.ImageIcon(getClass().getResource("/templarCoin/multimedia/blockChain.png")), jScrollPane1); // NOI18N

        txtBlochains.setColumns(20);
        txtBlochains.setRows(5);
        jScrollPane3.setViewportView(txtBlochains);

        jTabbedPane1.addTab("blockchain", jScrollPane3);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        tpTransaction.setPreferredSize(new java.awt.Dimension(260, 525));
        tpTransaction.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tpTransactionStateChanged(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setMinimumSize(new java.awt.Dimension(260, 450));
        jPanel1.setLayout(new java.awt.BorderLayout());

        pnTransaction.setPreferredSize(new java.awt.Dimension(109, 180));
        pnTransaction.setLayout(new java.awt.GridLayout(4, 1, 5, 5));

        jComboBox1.setEditable(true);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createTitledBorder("Eleitor"));
        pnTransaction.add(jComboBox1);

        jComboBox2.setEditable(true);
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.setBorder(javax.swing.BorderFactory.createTitledBorder("Candidato"));
        pnTransaction.add(jComboBox2);

        txtValue.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        txtValue.setText("0.0");
        txtValue.setBorder(javax.swing.BorderFactory.createTitledBorder("Value"));
        txtValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValueActionPerformed(evt);
            }
        });
        pnTransaction.add(txtValue);

        btRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/templarCoin/multimedia/cash-icon.png"))); // NOI18N
        btRegister.setText("Votar");
        btRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegisterActionPerformed(evt);
            }
        });
        pnTransaction.add(btRegister);

        jPanel1.add(pnTransaction, java.awt.BorderLayout.NORTH);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/templarCoin/multimedia/templarCoin.png"))); // NOI18N
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        tpTransaction.addTab("Votos", new javax.swing.ImageIcon(getClass().getResource("/templarCoin/multimedia/templar.png")), jPanel1); // NOI18N

        pnEleitores.setLayout(new java.awt.BorderLayout());

        lstUsers.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        lstUsers.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstUsers);

        pnEleitores.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jButton1.setText("Novo Eleitor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnEleitores.add(jButton1, java.awt.BorderLayout.PAGE_END);

        tpTransaction.addTab("Eleitores", new javax.swing.ImageIcon(getClass().getResource("/templarCoin/multimedia/users_ledger_24.png")), pnEleitores); // NOI18N

        pnCandidatos.setLayout(new java.awt.BorderLayout());

        lstCandidates.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        lstCandidates.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(lstCandidates);

        pnCandidatos.add(jScrollPane5, java.awt.BorderLayout.CENTER);

        jButton3.setText("Novo Candidato");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        pnCandidatos.add(jButton3, java.awt.BorderLayout.PAGE_END);

        tpTransaction.addTab("Candidatos", new javax.swing.ImageIcon(getClass().getResource("/templarCoin/multimedia/users_ledger_24.png")), pnCandidatos); // NOI18N

        getContentPane().add(tpTransaction, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tpTransactionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tpTransactionStateChanged
        if (tpTransaction.getSelectedComponent() == pnEleitores) {
            DefaultListModel model = new DefaultListModel();
            model.addAll(coin.getUsersBalance());
            lstUsers.setModel(model);
        }
    }//GEN-LAST:event_tpTransactionStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Create input fields
        JTextField nameField = new JTextField(10);
        JTextField ageField = new JTextField(10);
        JTextField idField = new JTextField(10);

        // Create a panel to hold input fields
        JPanel inputPanel = new JPanel(new GridLayout(3, 2));
        inputPanel.add(new JLabel("Nome: "));
        inputPanel.add(nameField);
        inputPanel.add(new JLabel("Idade: "));
        inputPanel.add(ageField);
        inputPanel.add(new JLabel("Id do Eleitor: "));
        inputPanel.add(idField);

        int result = JOptionPane.showConfirmDialog(
                this,
                inputPanel,
                "Insira os dados do eleitor",
                JOptionPane.OK_CANCEL_OPTION);

        if (result == JOptionPane.OK_OPTION) {
            // Get values from input fields
            String name = nameField.getText();
            int age = Integer.parseInt(ageField.getText());
            String id = idField.getText();

            // Create a Candidate
            Eleitor eleitor = new Eleitor(name, age, id);
	    
	    try {
            Transaction t = new Transaction(
                    "master",
                    name,
                    1.0
            );
            
            coin.add(t);
            txtLeger.setText(coin.toString());
            txtBlochains.setText(coin.getSecureLedger().toString());
            coin.save(fileTemplarCpoin);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            Logger.getLogger(TemplarCoinGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

            // You can perform further actions with the created candidate here.
            // For example, display the candidate's information.
            JOptionPane.showMessageDialog(this,
                    "Eleitor: " + eleitor.getNome() + ", ID: " + eleitor.getIdEleitor(),
                    "Criar Eleitor", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegisterActionPerformed
        try {
            /*Transaction t = new Transaction(
                /* txtFrom.getText(),
                txtTo.getText(),
                Double.valueOf(txtValue.getText())
            );

            coin.add(t);*/
            txtLeger.setText(coin.toString());
            txtBlochains.setText(coin.getSecureLedger().toString());
            coin.save(fileTemplarCpoin);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            Logger.getLogger(TemplarCoinGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btRegisterActionPerformed

    private void txtValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValueActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Create input fields
        JTextField nameField = new JTextField(10);
        JTextField ageField = new JTextField(10);
        JTextField idField = new JTextField(10);

        // Create a panel to hold input fields
        JPanel inputPanel = new JPanel(new GridLayout(3, 2));
        inputPanel.add(new JLabel("Nome: "));
        inputPanel.add(nameField);
        inputPanel.add(new JLabel("Idade: "));
        inputPanel.add(ageField);
        inputPanel.add(new JLabel("Id do Candidato: "));
        inputPanel.add(idField);

        int result = JOptionPane.showConfirmDialog(
                this,
                inputPanel,
                "Insira os dados do candidato",
                JOptionPane.OK_CANCEL_OPTION);

        if (result == JOptionPane.OK_OPTION) {
            // Get values from input fields
            String name = nameField.getText();
            int age = Integer.parseInt(ageField.getText());
            String id = idField.getText();

            // Create a Candidate
            Candidato candidato = new Candidato(name, age, id);
	    lista.getLista().add(candidato);
	    populateCand();
            // You can perform further actions with the created candidate here.
            // For example, display the candidate's information.
            JOptionPane.showMessageDialog(this,
                    "Candidato: " + candidato.getNome() + ", ID: " + candidato.getIdCandidato(), 
                    "Criar Candidato", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TemplarCoinGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TemplarCoinGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TemplarCoinGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TemplarCoinGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TemplarCoinGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRegister;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> lstCandidates;
    private javax.swing.JList<String> lstUsers;
    private javax.swing.JPanel pnCandidatos;
    private javax.swing.JPanel pnEleitores;
    private javax.swing.JPanel pnTransaction;
    private javax.swing.JTabbedPane tpTransaction;
    private javax.swing.JTextArea txtBlochains;
    private javax.swing.JTextArea txtLeger;
    private javax.swing.JTextField txtValue;
    // End of variables declaration//GEN-END:variables
}
